version: "3.7"

services:
  db:
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: galaxy
    ports:
      - 5432:5432
  janus1:
    image: bneibaruch/janus:latest
#    image: janus_bb:local
    restart: unless-stopped
    volumes:
      - ./misc/janus/config/dev:/usr/janusgxy/etc/janus
    ports:
      - 8088:8088
      - 7088:7088
      - 8188:8188
  mqtt:
    image: eclipse-mosquitto:1.6
    restart: unless-stopped
    ports:
      - 1883:1883
