no-hooks=true
no-tests=true
no-auto-timestamps=true
no-context=true
blacklist=["schema_migrations"]
[psql]
  dbname="galaxy"
  host="localhost"
  port=5432
  user="user"
  pass="password"
  sslmode="disable"
